(cl:in-package abstract_msgs-msg)
(cl:export '(LAYERNAME-VAL
          LAYERNAME
          ACTORVEC-VAL
          ACTORVEC
          SPACECONSTRAINT-VAL
          SPACECONSTRAINT
          XMIN-VAL
          XMIN
          XMAX-VAL
          XMAX
          YMIN-VAL
          YMIN
          YMAX-VAL
          YMAX
          ZMIN-VAL
          ZMIN
          ZMAX-VAL
          ZMAX
          LAYERTYPE-VAL
          LAYERTYPE
          TIMESTART-VAL
          TIMESTART
          TIMEEND-VAL
          TIMEEND
          FREQUENCY-VAL
          FREQUENCY
          EVENTMSGVEC-VAL
          EVENTMSGVEC
          ISSTOP-VAL
          ISSTOP
))