// Generated by gencpp from file rosplane_msgs/Formation.msg
// DO NOT EDIT!


#ifndef ROSPLANE_MSGS_MESSAGE_FORMATION_H
#define ROSPLANE_MSGS_MESSAGE_FORMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplane_msgs
{
template <class ContainerAllocator>
struct Formation_
{
  typedef Formation_<ContainerAllocator> Type;

  Formation_()
    : formation(0)  {
    }
  Formation_(const ContainerAllocator& _alloc)
    : formation(0)  {
  (void)_alloc;
    }



   typedef int8_t _formation_type;
  _formation_type formation;



  enum {
    ARROW = 0,
    STRAIGHT = 1,
  };


  typedef boost::shared_ptr< ::rosplane_msgs::Formation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplane_msgs::Formation_<ContainerAllocator> const> ConstPtr;

}; // struct Formation_

typedef ::rosplane_msgs::Formation_<std::allocator<void> > Formation;

typedef boost::shared_ptr< ::rosplane_msgs::Formation > FormationPtr;
typedef boost::shared_ptr< ::rosplane_msgs::Formation const> FormationConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplane_msgs::Formation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplane_msgs::Formation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosplane_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rosplane_msgs': ['/home/lee_firefly/catkin_ws/src/rosplane_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::Formation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::Formation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::Formation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::Formation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::Formation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::Formation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplane_msgs::Formation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99bfa9d80277f37210790ea2de15a518";
  }

  static const char* value(const ::rosplane_msgs::Formation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99bfa9d80277f372ULL;
  static const uint64_t static_value2 = 0x10790ea2de15a518ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplane_msgs::Formation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplane_msgs/Formation";
  }

  static const char* value(const ::rosplane_msgs::Formation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplane_msgs::Formation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# swarm formation\n\
\n\
int8 formation    #indicate the type of the formation   \n\
\n\
int8 ARROW = 0\n\
int8 STRAIGHT = 1\n\
";
  }

  static const char* value(const ::rosplane_msgs::Formation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplane_msgs::Formation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.formation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Formation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplane_msgs::Formation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplane_msgs::Formation_<ContainerAllocator>& v)
  {
    s << indent << "formation: ";
    Printer<int8_t>::stream(s, indent + "  ", v.formation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLANE_MSGS_MESSAGE_FORMATION_H
