// Generated by gencpp from file rosplane_msgs/MultiVaGoal.msg
// DO NOT EDIT!


#ifndef ROSPLANE_MSGS_MESSAGE_MULTIVAGOAL_H
#define ROSPLANE_MSGS_MESSAGE_MULTIVAGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace rosplane_msgs
{
template <class ContainerAllocator>
struct MultiVaGoal_
{
  typedef MultiVaGoal_<ContainerAllocator> Type;

  MultiVaGoal_()
    : goal()  {
    }
  MultiVaGoal_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MultiVaGoal_

typedef ::rosplane_msgs::MultiVaGoal_<std::allocator<void> > MultiVaGoal;

typedef boost::shared_ptr< ::rosplane_msgs::MultiVaGoal > MultiVaGoalPtr;
typedef boost::shared_ptr< ::rosplane_msgs::MultiVaGoal const> MultiVaGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosplane_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rosplane_msgs': ['/home/lee_firefly/catkin_ws/src/rosplane_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db43ffa02e592166bb4af6702f58b8c3";
  }

  static const char* value(const ::rosplane_msgs::MultiVaGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb43ffa02e592166ULL;
  static const uint64_t static_value2 = 0xbb4af6702f58b8c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplane_msgs/MultiVaGoal";
  }

  static const char* value(const ::rosplane_msgs::MultiVaGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
geometry_msgs/Point32[] goal\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::rosplane_msgs::MultiVaGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiVaGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplane_msgs::MultiVaGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplane_msgs::MultiVaGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLANE_MSGS_MESSAGE_MULTIVAGOAL_H
