(cl:in-package abstract_msgs-msg)
(cl:export '(XMIN-VAL
          XMIN
          XMAX-VAL
          XMAX
          YMIN-VAL
          YMIN
          YMAX-VAL
          YMAX
          ZMIN-VAL
          ZMIN
          ZMAX-VAL
          ZMAX
          TIMESTART-VAL
          TIMESTART
          TIMEEND-VAL
          TIMEEND
          FREQUENCY-VAL
          FREQUENCY
          SWARMID-VAL
          SWARMID
          TASKNAME-VAL
          TASKNAME
          ACTORNAME-VAL
          ACTORNAME
          ROBOTID-VAL
          ROBOTID
          DATATYPEVEC-VAL
          DATATYPEVEC
))