// Generated by gencpp from file abstract_msgs/ActiveActors.msg
// DO NOT EDIT!


#ifndef ABSTRACT_MSGS_MESSAGE_ACTIVEACTORS_H
#define ABSTRACT_MSGS_MESSAGE_ACTIVEACTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abstract_msgs
{
template <class ContainerAllocator>
struct ActiveActors_
{
  typedef ActiveActors_<ContainerAllocator> Type;

  ActiveActors_()
    : swarmName()
    , activeActorNames()  {
    }
  ActiveActors_(const ContainerAllocator& _alloc)
    : swarmName(_alloc)
    , activeActorNames(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _swarmName_type;
  _swarmName_type swarmName;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _activeActorNames_type;
  _activeActorNames_type activeActorNames;





  typedef boost::shared_ptr< ::abstract_msgs::ActiveActors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abstract_msgs::ActiveActors_<ContainerAllocator> const> ConstPtr;

}; // struct ActiveActors_

typedef ::abstract_msgs::ActiveActors_<std::allocator<void> > ActiveActors;

typedef boost::shared_ptr< ::abstract_msgs::ActiveActors > ActiveActorsPtr;
typedef boost::shared_ptr< ::abstract_msgs::ActiveActors const> ActiveActorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abstract_msgs::ActiveActors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abstract_msgs::ActiveActors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace abstract_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'abstract_msgs': ['/home/lee_firefly/catkin_ws/src/abstract_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::ActiveActors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::ActiveActors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::ActiveActors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "990553788e8fb33cf6c4579f7fbf2a45";
  }

  static const char* value(const ::abstract_msgs::ActiveActors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x990553788e8fb33cULL;
  static const uint64_t static_value2 = 0xf6c4579f7fbf2a45ULL;
};

template<class ContainerAllocator>
struct DataType< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abstract_msgs/ActiveActors";
  }

  static const char* value(const ::abstract_msgs::ActiveActors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string swarmName\n\
string[] activeActorNames\n\
";
  }

  static const char* value(const ::abstract_msgs::ActiveActors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.swarmName);
      stream.next(m.activeActorNames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActiveActors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abstract_msgs::ActiveActors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abstract_msgs::ActiveActors_<ContainerAllocator>& v)
  {
    s << indent << "swarmName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.swarmName);
    s << indent << "activeActorNames[]" << std::endl;
    for (size_t i = 0; i < v.activeActorNames.size(); ++i)
    {
      s << indent << "  activeActorNames[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.activeActorNames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABSTRACT_MSGS_MESSAGE_ACTIVEACTORS_H
