// Generated by gencpp from file abstract_msgs/LayerQuery.msg
// DO NOT EDIT!


#ifndef ABSTRACT_MSGS_MESSAGE_LAYERQUERY_H
#define ABSTRACT_MSGS_MESSAGE_LAYERQUERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <abstract_msgs/ActorQuery.h>

namespace abstract_msgs
{
template <class ContainerAllocator>
struct LayerQuery_
{
  typedef LayerQuery_<ContainerAllocator> Type;

  LayerQuery_()
    : layerName()
    , actorVec()
    , spaceConstraint(false)
    , xMin(0.0)
    , xMax(0.0)
    , yMin(0.0)
    , yMax(0.0)
    , zMin(0.0)
    , zMax(0.0)
    , layerType(0)
    , timeStart()
    , timeEnd()
    , frequency(0)
    , eventMsgVec()
    , isStop(false)  {
    }
  LayerQuery_(const ContainerAllocator& _alloc)
    : layerName(_alloc)
    , actorVec(_alloc)
    , spaceConstraint(false)
    , xMin(0.0)
    , xMax(0.0)
    , yMin(0.0)
    , yMax(0.0)
    , zMin(0.0)
    , zMax(0.0)
    , layerType(0)
    , timeStart(_alloc)
    , timeEnd(_alloc)
    , frequency(0)
    , eventMsgVec(_alloc)
    , isStop(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _layerName_type;
  _layerName_type layerName;

   typedef std::vector< ::abstract_msgs::ActorQuery_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::abstract_msgs::ActorQuery_<ContainerAllocator> >::other >  _actorVec_type;
  _actorVec_type actorVec;

   typedef uint8_t _spaceConstraint_type;
  _spaceConstraint_type spaceConstraint;

   typedef double _xMin_type;
  _xMin_type xMin;

   typedef double _xMax_type;
  _xMax_type xMax;

   typedef double _yMin_type;
  _yMin_type yMin;

   typedef double _yMax_type;
  _yMax_type yMax;

   typedef double _zMin_type;
  _zMin_type zMin;

   typedef double _zMax_type;
  _zMax_type zMax;

   typedef int32_t _layerType_type;
  _layerType_type layerType;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timeStart_type;
  _timeStart_type timeStart;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timeEnd_type;
  _timeEnd_type timeEnd;

   typedef int32_t _frequency_type;
  _frequency_type frequency;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _eventMsgVec_type;
  _eventMsgVec_type eventMsgVec;

   typedef uint8_t _isStop_type;
  _isStop_type isStop;





  typedef boost::shared_ptr< ::abstract_msgs::LayerQuery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abstract_msgs::LayerQuery_<ContainerAllocator> const> ConstPtr;

}; // struct LayerQuery_

typedef ::abstract_msgs::LayerQuery_<std::allocator<void> > LayerQuery;

typedef boost::shared_ptr< ::abstract_msgs::LayerQuery > LayerQueryPtr;
typedef boost::shared_ptr< ::abstract_msgs::LayerQuery const> LayerQueryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abstract_msgs::LayerQuery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abstract_msgs::LayerQuery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace abstract_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'abstract_msgs': ['/home/lee_firefly/catkin_ws/src/abstract_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::LayerQuery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::LayerQuery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::LayerQuery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f055341a31be956bd0e168a756124afc";
  }

  static const char* value(const ::abstract_msgs::LayerQuery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf055341a31be956bULL;
  static const uint64_t static_value2 = 0xd0e168a756124afcULL;
};

template<class ContainerAllocator>
struct DataType< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abstract_msgs/LayerQuery";
  }

  static const char* value(const ::abstract_msgs::LayerQuery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string layerName\n\
\n\
ActorQuery[] actorVec\n\
\n\
bool spaceConstraint\n\
float64 xMin\n\
float64 xMax\n\
float64 yMin\n\
float64 yMax\n\
float64 zMin\n\
float64 zMax\n\
\n\
int32 layerType\n\
\n\
string timeStart\n\
string timeEnd\n\
\n\
int32 frequency\n\
\n\
string[] eventMsgVec\n\
\n\
bool isStop\n\
================================================================================\n\
MSG: abstract_msgs/ActorQuery\n\
int32 swarmID\n\
string taskName\n\
string actorName\n\
int32 robotID\n\
string[] dataTypeVec\n\
";
  }

  static const char* value(const ::abstract_msgs::LayerQuery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.layerName);
      stream.next(m.actorVec);
      stream.next(m.spaceConstraint);
      stream.next(m.xMin);
      stream.next(m.xMax);
      stream.next(m.yMin);
      stream.next(m.yMax);
      stream.next(m.zMin);
      stream.next(m.zMax);
      stream.next(m.layerType);
      stream.next(m.timeStart);
      stream.next(m.timeEnd);
      stream.next(m.frequency);
      stream.next(m.eventMsgVec);
      stream.next(m.isStop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LayerQuery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abstract_msgs::LayerQuery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abstract_msgs::LayerQuery_<ContainerAllocator>& v)
  {
    s << indent << "layerName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.layerName);
    s << indent << "actorVec[]" << std::endl;
    for (size_t i = 0; i < v.actorVec.size(); ++i)
    {
      s << indent << "  actorVec[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::abstract_msgs::ActorQuery_<ContainerAllocator> >::stream(s, indent + "    ", v.actorVec[i]);
    }
    s << indent << "spaceConstraint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.spaceConstraint);
    s << indent << "xMin: ";
    Printer<double>::stream(s, indent + "  ", v.xMin);
    s << indent << "xMax: ";
    Printer<double>::stream(s, indent + "  ", v.xMax);
    s << indent << "yMin: ";
    Printer<double>::stream(s, indent + "  ", v.yMin);
    s << indent << "yMax: ";
    Printer<double>::stream(s, indent + "  ", v.yMax);
    s << indent << "zMin: ";
    Printer<double>::stream(s, indent + "  ", v.zMin);
    s << indent << "zMax: ";
    Printer<double>::stream(s, indent + "  ", v.zMax);
    s << indent << "layerType: ";
    Printer<int32_t>::stream(s, indent + "  ", v.layerType);
    s << indent << "timeStart: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timeStart);
    s << indent << "timeEnd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timeEnd);
    s << indent << "frequency: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frequency);
    s << indent << "eventMsgVec[]" << std::endl;
    for (size_t i = 0; i < v.eventMsgVec.size(); ++i)
    {
      s << indent << "  eventMsgVec[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.eventMsgVec[i]);
    }
    s << indent << "isStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isStop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABSTRACT_MSGS_MESSAGE_LAYERQUERY_H
