// Generated by gencpp from file abstract_msgs/StationData.msg
// DO NOT EDIT!


#ifndef ABSTRACT_MSGS_MESSAGE_STATIONDATA_H
#define ABSTRACT_MSGS_MESSAGE_STATIONDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abstract_msgs
{
template <class ContainerAllocator>
struct StationData_
{
  typedef StationData_<ContainerAllocator> Type;

  StationData_()
    : uavID()
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
    }
  StationData_(const ContainerAllocator& _alloc)
    : uavID(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _uavID_type;
  _uavID_type uavID;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::abstract_msgs::StationData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abstract_msgs::StationData_<ContainerAllocator> const> ConstPtr;

}; // struct StationData_

typedef ::abstract_msgs::StationData_<std::allocator<void> > StationData;

typedef boost::shared_ptr< ::abstract_msgs::StationData > StationDataPtr;
typedef boost::shared_ptr< ::abstract_msgs::StationData const> StationDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abstract_msgs::StationData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abstract_msgs::StationData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace abstract_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'abstract_msgs': ['/home/lee_firefly/catkin_ws/src/abstract_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::StationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::StationData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::StationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::StationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::StationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::StationData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abstract_msgs::StationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57fdd61b8887a09939e92391e5860872";
  }

  static const char* value(const ::abstract_msgs::StationData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57fdd61b8887a099ULL;
  static const uint64_t static_value2 = 0x39e92391e5860872ULL;
};

template<class ContainerAllocator>
struct DataType< ::abstract_msgs::StationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abstract_msgs/StationData";
  }

  static const char* value(const ::abstract_msgs::StationData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abstract_msgs::StationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string uavID\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
";
  }

  static const char* value(const ::abstract_msgs::StationData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abstract_msgs::StationData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uavID);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StationData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abstract_msgs::StationData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abstract_msgs::StationData_<ContainerAllocator>& v)
  {
    s << indent << "uavID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uavID);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABSTRACT_MSGS_MESSAGE_STATIONDATA_H
