// Generated by gencpp from file abstract_msgs/UnifiedData.msg
// DO NOT EDIT!


#ifndef ABSTRACT_MSGS_MESSAGE_UNIFIEDDATA_H
#define ABSTRACT_MSGS_MESSAGE_UNIFIEDDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace abstract_msgs
{
template <class ContainerAllocator>
struct UnifiedData_
{
  typedef UnifiedData_<ContainerAllocator> Type;

  UnifiedData_()
    : swarmID(0)
    , taskName()
    , actorName()
    , robotID(0)
    , timeStamp()
    , robotPose()
    , sensorPose()
    , dataType()
    , data()  {
    }
  UnifiedData_(const ContainerAllocator& _alloc)
    : swarmID(0)
    , taskName(_alloc)
    , actorName(_alloc)
    , robotID(0)
    , timeStamp(_alloc)
    , robotPose(_alloc)
    , sensorPose(_alloc)
    , dataType(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _swarmID_type;
  _swarmID_type swarmID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _taskName_type;
  _taskName_type taskName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _actorName_type;
  _actorName_type actorName;

   typedef int32_t _robotID_type;
  _robotID_type robotID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timeStamp_type;
  _timeStamp_type timeStamp;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robotPose_type;
  _robotPose_type robotPose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _sensorPose_type;
  _sensorPose_type sensorPose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dataType_type;
  _dataType_type dataType;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::abstract_msgs::UnifiedData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abstract_msgs::UnifiedData_<ContainerAllocator> const> ConstPtr;

}; // struct UnifiedData_

typedef ::abstract_msgs::UnifiedData_<std::allocator<void> > UnifiedData;

typedef boost::shared_ptr< ::abstract_msgs::UnifiedData > UnifiedDataPtr;
typedef boost::shared_ptr< ::abstract_msgs::UnifiedData const> UnifiedDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abstract_msgs::UnifiedData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abstract_msgs::UnifiedData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace abstract_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'abstract_msgs': ['/home/lee_firefly/catkin_ws/src/abstract_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abstract_msgs::UnifiedData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abstract_msgs::UnifiedData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abstract_msgs::UnifiedData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48cec9a0486f5d717da700cd21865426";
  }

  static const char* value(const ::abstract_msgs::UnifiedData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48cec9a0486f5d71ULL;
  static const uint64_t static_value2 = 0x7da700cd21865426ULL;
};

template<class ContainerAllocator>
struct DataType< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abstract_msgs/UnifiedData";
  }

  static const char* value(const ::abstract_msgs::UnifiedData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 swarmID\n\
string taskName\n\
string actorName\n\
int32 robotID\n\
string timeStamp\n\
geometry_msgs/Pose robotPose\n\
geometry_msgs/Pose sensorPose\n\
string dataType\n\
uint8[] data\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::abstract_msgs::UnifiedData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.swarmID);
      stream.next(m.taskName);
      stream.next(m.actorName);
      stream.next(m.robotID);
      stream.next(m.timeStamp);
      stream.next(m.robotPose);
      stream.next(m.sensorPose);
      stream.next(m.dataType);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnifiedData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abstract_msgs::UnifiedData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abstract_msgs::UnifiedData_<ContainerAllocator>& v)
  {
    s << indent << "swarmID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.swarmID);
    s << indent << "taskName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.taskName);
    s << indent << "actorName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.actorName);
    s << indent << "robotID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robotID);
    s << indent << "timeStamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timeStamp);
    s << indent << "robotPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robotPose);
    s << indent << "sensorPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.sensorPose);
    s << indent << "dataType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dataType);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABSTRACT_MSGS_MESSAGE_UNIFIEDDATA_H
